---
title: "Case Study"
author: "Miguel Bonilla and Kendall Scott"
date: "3/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
#Data analysis on craft beers and breweries accross the United States.
#Project is created with: R 4.1.2
#Packages: caret, class, gganimate, ggrepel, ggthemes, gifski, kableExtra, maps, tidyverse, tigris, viridis

```{r}
#Question 2 & 3
library(dplyr)
library(tidyr)
library(tidyverse)
#reading in the csvs
brewery = read.csv("Data Files/breweries.csv") #read breweries.csv
beer = read.csv("Data Files/beers.csv") #read beers.csv

#renaming columns for the join to the beer dataset
brewery=rename(brewery, Brewery_id=Brew_ID, Brewery=Name)
brewery$State <- trimws(brewery$State, which = c("left"))#added to remove space before state

#pulling ids with inaccurate info
Brewery_id<-as.integer(c(96,415,167, 262, 139))
error_brew_ids<-as.data.frame(Brewery_id)
#joining to get Brewery Names
brew_filter = merge(x=error_brew_ids,y=brewery,by="Brewery_id") %>% select(Brewery_id, Brewery)

#joining on brewery name to pull in correct columns--filter out inaccurate
brew_filter = merge(x=brewery,y=brew_filter,by="Brewery") %>% mutate(type = case_when( Brewery_id.x==Brewery_id.y ~ "correct",TRUE~  "wrong"))
#filtering down to rows with errors
brew_replace =brew_filter %>%filter(type == "wrong") %>% select(Brewery_id.y, Brewery, City, State)%>% rename(Brewery_id=Brewery_id.y)

#removing errors and replacing with updated df
brewery = anti_join(x=brewery,y=error_brew_ids,by="Brewery_id")
brewery<-rbind(brewery, brew_replace)
brewery$City = str_replace(brewery$City, "Menominie", "Menomonie")

#join between brewery and beer data
beer_brewery = merge(x=brewery,y=beer,by="Brewery_id")

#print first 6 rows
head(beer_brewery)
#print last 6 rows
tail(beer_brewery)

#filtering of NAs for ABV and IBU-- rows drop from 2410 down to 1405 for this filtering
#only use this filtered dataset for the questions related to ABV/IBU
clean_beer_brewery <- beer_brewery %>% filter_at(vars(ABV,IBU),all_vars(!is.na(.)))
```


```{r}
#question 1
#How many breweries are present in each state? (counties heatmap)
#load libraries
library(ggplot2)
library(maps)
#library(tidyverse)#added to 1st chunk
library(ggthemes)
library(kableExtra)
#load counties table
cnty <- read.csv("Data Files/cty-cnty.csv")
colnames(cnty)[3] <- "region"
#load population data 2021
pop_est <- read.csv("Data Files/NST-EST2021-alldata.csv")
pop_est <- pop_est %>% select(NAME,POPESTIMATE2021) %>% rename(region=NAME, "Pop2021"=POPESTIMATE2021) %>% mutate(region=tolower(region))
pop_est <- pop_est[-c(1:5),]
pop_est$region %>% str_replace("District of Columbia", "washington, d.c.")
pop_est$rank <- rank(-pop_est$Pop2021)

#wrangle data
#brewery$State <- trimws(brewery$State, which = c("left"))
cnty <- cnty %>% select("City", "State","County","region")#select columns
cnty <- cnty[!duplicated(cnty),]


#left join brew and cnty
brewcomb <- merge(brewery, select(cnty, c("City", "State", "County","region")), by=c("City","State"))
brewcomb <- brewcomb %>% distinct(Brewery_id, .keep_all = TRUE)

#1 table wtih state count, map with state count and map with county count
#state and county tables
us_states <- map_data("state")
us_counties <- map_data("county")

#state brewery count
brew_state <- brewcomb %>% mutate(region=tolower(region)) %>%
  group_by(region) %>% count(region)
brew_state <- brew_state %>% left_join(pop_est,by="region") %>% arrange(desc(n))
brew_state %>% mutate(region=str_to_title(region),Pop2021=round(Pop2021/1000000,2)) %>% kable(col.names = c("State","Breweries","Population 2021","Pop. Rank")) %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  row_spec(row = 0, italic = T, background = "#21918c", color = "white") %>% 
  column_spec(1:2, width = "0.5in")
#state gradient map
us_states %>% left_join(brew_state,by=("region")) %>% 
  ggplot(aes(x=long,y=lat,group=group,fill=n))+
  geom_polygon(color = "gray90", size=.1)+
  coord_map(projection = "albers", lat0=45, lat1=55)+
  scale_fill_viridis_c()+
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        axis.title = element_blank())+
  labs(fill="Brewery\nCount")+
  ggtitle("Breweries by State\nContinental US")

#county brewery count
brew_county <- brewcomb %>% mutate(subregion=tolower(County)) %>% 
  group_by(subregion) %>% count(subregion)
#county gradient map
us_counties %>% left_join(brew_county,by="subregion") %>%
  ggplot()+
  geom_polygon(aes(x=long,y=lat,group=group,fill=n),color = "gray90",size=.1)+
  coord_map(projection = "albers",lat0=45,lat1=55)+
  scale_fill_viridis_c()+
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        axis.title = element_blank())+
  labs(fill="Brewery\nCount")+
  ggtitle("Breweries by County\nContinental US")+
  geom_polygon(data = us_states,aes(x=long,y=lat,group=group), color = "white",size=.15,fill="transparent")
```

```{r}
#Question 4
#Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.

#ABV
bb<-clean_beer_brewery %>% group_by(State) %>% summarize(medianABV = median(ABV), count = n()) %>% ggplot(aes(x = reorder(State, -medianABV), y = medianABV, fill=medianABV)) + geom_col()+ 
  xlab('State') + ylab('Median ABV')+ggtitle("Median ABV by State") +theme(axis.text = element_text(size = 6))+ scale_fill_gradient(low='#46085C', high='#4FBA6E', name='Median ABV')
bb + scale_y_continuous(labels = scales::percent)

#IBU
bb<-clean_beer_brewery %>% group_by(State) %>% summarize(medianABV = median(ABV), medianIBU=round(median(IBU),0), count = n()) %>% ggplot(aes(x = reorder(State, -medianABV), y = medianIBU, fill=medianIBU)) + geom_col()+ 
  xlab('State') + ylab('Median IBU')+ggtitle("Median IBU by State") +theme(axis.text = element_text(size = 6))+ scale_fill_gradient(low='#46085C', high='#4FBA6E', name='Median IBU')
bb 

#combined
bb<-clean_beer_brewery %>% group_by(State) %>% summarize(medianABV = median(ABV), medianIBU=round(median(IBU),0), count = n()) %>% ggplot(aes(x = reorder(State, -medianABV), y = medianABV, fill=medianIBU)) + geom_col()+ 
  xlab('State') + ylab('Median ABV')+ggtitle("Median IBU/ABV by State") +theme(axis.text = element_text(size = 6))+ scale_fill_gradient(low='#46085C', high='#4FBA6E', name='Median IBU')
bb + scale_y_continuous(labels = scales::percent)
```

```{r}
library(kableExtra)
#5 which state has the maximum alcoholic (ABV) beer? which state has the most bitter (IBU) beer?

#maximum ABV by state
maxABV <- beer_brewery %>% merge(cnty, by=c("City", "State")) %>% select(ABV, region) %>% 
  filter(!is.na(ABV)) %>% group_by(region) %>% summarise(Max_ABV=max(ABV)) %>% arrange(desc(Max_ABV))
maxABV %>% kable(col.names = c("State", "Max ABV")) %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  row_spec(row = 0, italic = T, background = "#21918c", color = "white") %>% 
  column_spec(1:2, width = "0.5in")

#Maximum IBU by state
maxIBU <- beer_brewery %>% merge(cnty, by=c("City", "State")) %>% select(IBU, region) %>% 
  filter(!is.na(IBU)) %>% group_by(region) %>% summarise(Max_IBU=max(IBU)) %>% arrange(desc(Max_IBU))
maxIBU %>% kable(col.names = c("State","Max IBU")) %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  row_spec(row = 0, italic = T, background = "#21918c", color = "white") %>% 
  column_spec(1:2, width = "0.5in")

#US map for Max ABV by state
us_states %>% mutate(region=str_to_title(region)) %>% left_join(maxABV,by="region") %>% 
  ggplot(aes(x=long,y=lat,group=group, fill = Max_ABV))+
  geom_polygon(color = "gray90", size=.1)+
  coord_map(projection = "albers", lat0=45, lat1=55)+
  scale_fill_viridis_c()+
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        axis.title = element_blank())+
  labs(fill="Maximum\nAlcohol by Volume")+
  ggtitle("Maximum ABV by State\nContinental US")

#US map for max IBU by state
us_states %>% mutate(region=str_to_title(region)) %>% left_join(maxIBU,by="region") %>% 
  ggplot(aes(x=long,y=lat,group=group, fill = Max_IBU))+
  geom_polygon(color = "gray90", size=.1)+
  coord_map(projection = "albers", lat0=45, lat1=55)+
  scale_fill_viridis_c()+
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        axis.title = element_blank())+
  labs(fill="Maximum\nIBU")+
  ggtitle("Maximum IBU by State\nContinental US")

```

```{r}
#Question 6
#6 comment on the summary statistics and distribution of the ABV variable

#Density Curve for ABV
beer_brewery %>% ggplot(aes(x=ABV))+geom_density(color="#39568C")+theme_bw()+theme(
  panel.grid = element_blank(),
  panel.border = element_blank())
#Boxplot for ABV
beer_brewery %>% ggplot(aes(x=ABV))+geom_boxplot()

#5 number summary and mean for ABV
ABVsum <- beer_brewery %>% filter(!is.na(ABV)) %>% 
  select(ABV) %>%
  summarise(min=min(ABV),
            "25%"=quantile(ABV,.25),
            median=median(ABV),
            "75%"=quantile(ABV,.75),
            max=max(ABV),mean=mean(ABV))
ABVsum %>% kable(col.names = c("Min", "25%", "Med", "75%", "Max", "Mean")) %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  row_spec(row = 0, italic = T, background = "#21918c", color = "white") %>% 
  column_spec(1:2, width = "0.5in")

#right skewed distribution centered at .057, there seems to be some degree of rounding occuring at around .1, 
#given that there are several beers that are exactly at the line with fewer slightly below and almost none 
#slightly above the number. There also seems to be some degree of rounding at .5, but this is less pronounced
```
```{r}
#Question 7
#7.Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot. Make your best judgment of a relationship and EXPLAIN your answer.

#comparison of ABV/IBU in scatter plot with regression line
bb = clean_beer_brewery %>% ggplot(aes(x = ABV, y=IBU, color = IBU)) + geom_point(aes(fill=IBU, color=IBU),pch=21,size=3,colour="black")+ ggtitle("International Bitterness Units vs. Alchohol by Volume")+ 
  geom_smooth(method='lm', formula= y~x, color="black")
bb + scale_x_continuous(labels = scales::percent)

```

```{r}
#Question 8
library(caret)
library(class)

#Budweiser would also like to investigate the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with “Ale” in its name other than IPA).  You decide to use KNN classification to investigate this relationship.  Provide statistical evidence one way or the other. You can of course assume your audience is comfortable with percentages … KNN is very easy to understand conceptually.

#add ipa, ale, other column
ipa_ale <-
  clean_beer_brewery %>% mutate(Ale_type = ifelse(
    str_detect(clean_beer_brewery$Style, regex("ipa", ignore_case = TRUE)),
    "IPA",
    ifelse(str_detect(
      clean_beer_brewery$Style, regex("ale", ignore_case = TRUE)
    ), "Ale", "other")
  ))
#filter out "other" type of beers and drop levels
ipa_ale <- ipa_ale %>% filter(Ale_type %in% c("IPA", "Ale")) %>% droplevels(ipa_ale$Ale_type)

#for loops for KNN model and hypertuning k parameter
nsplits <- 100
nks <- 30

df <- data.frame()
set.seed(6)
for (i in 1:nsplits) {
  n <- nrow(ipa_ale)
  nsamp <- sample(1:n,round(n*.7)) #for a 70-30 split
  ipa_train <- ipa_ale[nsamp,]
  ipa_test <- ipa_ale[-nsamp,]
  
  for (j in 1:nks) {
    cm <- knn(scale(ipa_train[,7:8]),scale(ipa_test[,7:8]),cl=ipa_train$Ale_type,k=i) %>% confusionMatrix(as.factor(ipa_test$Ale_type),positive = "IPA")
    cm_values <- data.frame("k"=j,"Accuracy"=cm$overall[1],"Sensitivity"=cm$byClass[1],"Specificity"=cm$byClass[2])
    df <- rbind(df,cm_values)
  }
}

#summarize the k results
means <- df %>% group_by(k) %>% summarise(Accuracy=mean(Accuracy)*100,Sensitivity=mean(Sensitivity)*100,Specificity=mean(Specificity)*100)

#plot accuracy, sensitivity and specificity
means %>% ggplot(aes(x=k,y=Accuracy))+geom_line(color="#39568C")+theme_bw()+theme(
  panel.grid = element_blank(),
  panel.border = element_blank())
means %>% ggplot(aes(x=k,y=Sensitivity))+geom_line(color="#39568C")+theme_bw()+theme(
  panel.grid = element_blank(),
  panel.border = element_blank())
means %>% ggplot(aes(x=k,y=Specificity))+geom_line(color="#39568C")+theme_bw()+theme(
  panel.grid = element_blank(),
  panel.border = element_blank())

#After hypertuning the k parameter, we can see that looking at the 14 closest beers in terms of ABV and IBU would help us make a prediction on whether it's a Indian Pale Ale or a nother type of Ale, with about 85% accuracy.
#Moreover, this model is able to properly classify IPAs 85.98% of the time
```

```{r}
#Question 9
#Knock their socks off!  Find one other useful inference from the data that you feel Budweiser may be able to find value in.  You must convince them why it is important and back up your conviction with appropriate statistical evidence. 

#join brew/beer and cnty (bubble map data for brews)
library(tidyverse)
library(tigris)

us_counties <- map_data("county")
colnames(cnty)[3] <- "region"
cnty<-cnty%>% select(City, State, region, County)
cnty<- cnty %>% distinct(City, State, .keep_all = TRUE)
us_counties<-us_counties %>% distinct(region, subregion, .keep_all = TRUE)
  
brewcomb_type <- merge(clean_beer_brewery, select(cnty, c("City", "State", "County","region")), by=c("City","State"))
brewcomb_type <- brewcomb_type %>% mutate(subregion=tolower(County),region=tolower(region))

#combining for lat long info
brewcomb_type <- merge(brewcomb_type, select(us_counties, c("lat", "long", "region","subregion")), by=c("region","subregion"))

#style text clean-up
library(stringr)

brewcomb_type$BeerStyle <- str_replace_all(brewcomb_type$Style, c(".*American.*IPA.*"="_American IPA",  ".*American.*Ale.*"= "_American Ale", ".*Stout.*"="_Stout",  ".*Lager.*"="_Lager",  ".*Pilsner.*"= "_Pilsner", ".*Bitter.*"= "_Bitter", ".*Porter.*"= "_Porter", ".*Belgian.*"= "_German",  ".*Bock.*"= "_German",   ".*Czech.*"= "_German", ".*Doppelbock.*"= "_German",  ".*German.*"= "_German",  ".*Gose.*"= "_German",  ".*Grisette.*"= "_German",  ".*Hefeweizen.*"= "_German",  ".*Kölsch.*"= "_German",  ".*Maibock.*"= "_German",  ".*Märzen.*"= "_German",  ".*Munich.*"= "_German",  ".*Saison.*"= "_German",  ".*Vienna.*"= "_German",  ".*Witbier.*"= "_German",  ".*Altbier.*"= "_German", ".*Baltic.*"= "_German",  ".*Berliner.*"= "_German",  ".*Keller.*"= "_German", ".*Schwarzbier.*"= "_German"))
brewcomb_type$BeerStyle<-str_replace(brewcomb_type$BeerStyle,"^(?!_).*$", "")
brewcomb_type$SimpleStyle<-str_replace(brewcomb_type$Style,".*Ale.*", "_Ale")
brewcomb_type$SimpleStyle<-str_replace(brewcomb_type$SimpleStyle,"^(?!_).*$", "")
brewcomb_type$BeerStyle <- paste(brewcomb_type$BeerStyle, brewcomb_type$SimpleStyle)
brewcomb_type$BeerStyle<-str_replace(brewcomb_type$BeerStyle,".*_American Ale _Ale.*", "_American Ale")
brewcomb_type$BeerStyle <- trimws(brewcomb_type$BeerStyle, which = c("left"))#added to remove space before style
brewcomb_type$BeerStyle<-str_replace(brewcomb_type$BeerStyle,"^(?!_).*$", "Other")
brewcomb_type$BeerStyle <- str_replace_all(brewcomb_type$BeerStyle, c(".*_"=" ", ".*German.*Ale.*"="German Ale", ".*American.*IPA.*"="American IPA"))
brewcomb_type$BeerStyle <- trimws(brewcomb_type$BeerStyle, which = c("right"))#added to remove space after style
brewcomb_type$BeerStyle <- trimws(brewcomb_type$BeerStyle, which = c("left"))#added to remove space before style

#summary of beer styles
sum_brew<-brewcomb_type %>% group_by(BeerStyle) %>% summarize(meanabv = mean(ABV), meanIBU = mean(IBU), beers = n()) %>% arrange(desc(beers))
sum_brew

#summary table for powerpoint
sum_brew %>% kable(col.names = c("BeerStyle","meanabv","meanIBU","beers")) %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  row_spec(row = 0, italic = T, background = "#21918c", color = "white") %>% 
  column_spec(1:2, width = "0.5in")

#summary table for bubble graph/map
bb<-brewcomb_type %>% group_by(BeerStyle, lat, long) %>% summarize(meanabv = mean(ABV), meanIBU = mean(IBU), beers = n()) %>% arrange(desc(beers))
bb

# Beer Style bubble map fixed
library(ggrepel)
usa <- map_data("state")
ggplot() +
  geom_polygon(data = usa, aes(x=long, y = lat, group = group),color = "white", fill="grey", alpha=0.3) +
  geom_point( data=bb, aes(x=long, y=lat, color=BeerStyle, size=beers,  alpha=0.5)) +
  scale_color_viridis(option="viridis", discrete=TRUE, name="Beer Style" ) +
  theme_void() +
  scale_size(range = c(1, 10), name=" # of beers")+
  ggtitle("Number of Beers by Style")

#animation of bubble graph using map and simplified beer styles
library(gganimate)
library(gifski)
p <- ggplot() +
  geom_polygon(data = usa, aes(x=long, y = lat, group = group),color = "white", fill="grey", alpha=0.3) +
  geom_point( data=bb, aes(x=long, y=lat, color=BeerStyle, size=beers,  alpha=0.5)) +
  scale_color_viridis_d(option="viridis", name="Beer Style" ) +
  theme_void() +
  scale_size(range = c(2, 20), name=" # of beers")+
  ggtitle("Number of Beers by Style\n {closest_state}")+
  theme(text = element_text(size=20))+
  transition_states(BeerStyle) +
  enter_fade() + 
  enter_grow() +
  ease_aes('sine-in-out')
animate(p, width = 900, height = 572, duration = 14)
 
#boxplots by Beer Style
#boxplot by ABV/Style
gg<-ggplot(brewcomb_type, aes(x = BeerStyle, y = ABV, fill = BeerStyle)) +
  geom_boxplot() +
  theme_classic()
gg+coord_flip()+ scale_fill_viridis(option="magma", discrete=TRUE, name="Beer Style" )

#boxplot by IBU/Style
gg<-ggplot(brewcomb_type, aes(x = BeerStyle, y = IBU, fill = BeerStyle)) +
  geom_boxplot() +
  theme_classic()
gg+coord_flip()+ scale_fill_viridis(option="magma", discrete=TRUE, name="Beer Style" )

# knit together pngs into gif for powerpoint
library(magick)
list.files(path='//Users/macowner/Desktop/Data Science/gif//', pattern = '*.png', full.names = TRUE) %>% 
  image_read() %>% # reads each path file
  image_join() %>% # joins image
  image_animate(fps=4) %>% # animates, can opt for number of loops
  image_write("FileName.gif") # write to current dir

#ipa mapping
ipa<-brewcomb_type%>% filter(BeerStyle=="American IPA") %>% group_by(BeerStyle, lat, long) %>% summarize(meanabv = mean(ABV), meanIBU = mean(IBU), beers = n()) %>% arrange(desc(beers))
ipa

ggplot() +
  geom_polygon(data = usa, aes(x=long, y = lat, group = group),color = "white", fill="grey", alpha=0.3) +
  geom_point( data=ipa, aes(x=long, y=lat, color=meanIBU, size=beers,  alpha=0.5)) +
  scale_color_viridis(option="viridis",  name="IBU" ) +
  theme_void() +
  scale_size(range = c(1, 10), name=" # of beers")+
  ggtitle("Number of American IPA Beers")



```





